---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neon-operator
  namespace: neon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neon-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get
  - apiGroups:
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - neon.oltp.molnett.org
    resources:
      - clusters
      - clusters/status
      - clusters/finalizers
      - pageservers
      - pageservers/status
      - pageservers/finalizers
      - projects
      - projects/status
      - projects/finalizers
      - branches
      - branches/status
      - branches/finalizers
      - safekeepers
      - safekeepers/status
      - safekeepers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neon-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neon-operator
subjects:
  - kind: ServiceAccount
    name: neon-operator
    namespace: neon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neon-operator
  namespace: neon
  labels:
    app: neon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neon-operator
  template:
    metadata:
      labels:
        app: neon-operator
    spec:
      serviceAccountName: neon-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: operator
          image: stackblaze/neon-operator:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: neon-operator
  namespace: neon
spec:
  selector:
    app: neon-operator
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---

